### ISSUE TITLE
Edit some new stuff

### ISSUE THREAD

**Issue by Hasthikagirihagama** [Hasthikagirihagama/Myweb#5]
Edit the newly updated stuff on 
[https://hasthikagirihagama.github.io/](url)

**Comment by ajjju1** [comment]
hey @Hasthikagirihagama can you be more spcecific.

**Comment by Hasthikagirihagama** [comment]
sorry @ajjju1  this is one of my personal repo so I just create my own issues

**Comment by ajjju1** [comment]
it's ok not a problem
